### ISSUE TITLE
Chapter 1, Pg 21 Case 4 nad more - references mdp02.py but thr file does not exist?

### ISSUE THREAD

**Issue by StevenWillett** [PacktPublishing/Artificial-Intelligence-By-Example#1]
I have recently purchased the second edition of the printed book and on page 21 under Cases 4, it references the file `mdp02.py`, but I cannot find the file which makes me wonder, this early on is there going to be more missing references I should be aware of?

Is there an errata available?

**Comment by Denis2054** [comment]
Thank you for your comment. 
You are right. The file was missing. 
I uploaded mdp02.py to the Chapter01 directory.
When you run it, it will ask you for a starting number limited to the size of the array.
It's an experimental program.
However, since Transformer models (ChatGPT, for example) have emerged, the exercise I foresaw makes sense.
A transformer handles any kind of sequence (words, numbers, sounds).
But so does a Markov Decision Process, which remains a remarkable algorithm!
